# This is a basic workflow to help you get started with Actions

name: GetSource

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/3 * * *'
    
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git pull
          git config --global user.email "aaa@gmail.com"
          git config --global user.name "aaa"
      
      
      - name: Main
        run: |
          pwd
          #chmod +x autorun.sh
          #./autorun.sh
          wget https://epg.pw/test_channels_taiwan.txt
          wget https://raw.githubusercontent.com/hus888yu/app/main/666.txt
          wget https://raw.githubusercontent.com/alantang1977/X/main/LIVE/晴天.txt

          mv ./晴天.txt ./ETH_cn.txt
          
          awk 'NR>12' ./test_channels_taiwan.txt > epg_tw.txt

          echo "外國,#genre#" > movie.txt
          echo "第四台,#genre#" > TV_TW.txt

          #wget https://epg.pw/test_channels_united_states.txt
          #wget https://epg.pw/test_channels_movies.txt

          
          #grep "Star Movie" ./test_channels_united_states.txt >> movie.txt
          #grep "HBO HD" ./test_channels_united_states.txt >> movie.txt
          #grep "hbo2" ./test_channels_united_states.txt >> movie.txt
          #grep "HBO Family" ./test_channels_united_states.txt >> movie.txt
          #grep "HBO Signature" ./test_channels_united_states.txt >> movie.txt
          
          #grep "Cinemax" ./test_channels_movies.txt >> movie.txt
          #grep "HBO 2"  ./test_channels_movies.txt >> movie.txt
          #grep "HBO 3"  ./test_channels_movies.txt >> movie.txt

          #wget https://raw.githubusercontent.com/linitfor/MyTV/main/TW_only.txt
          #head -n 140 ./TW_only.txt > ytnew.txt
          #cat ./TW_only.txt > ytnew.txt

          #cat movie.txt  epg_tw.txt > TV1.txt 
          #cat ytnew.txt  TV1.txt > TV.txt
          #sed -i 's/\[geo\-blocked\]//' ./TV.txt
          #sed -i 's/Beyond//' ./TV.txt
          
          #rm -rf ./test_channels_taiwan.txt*
          #rm -rf ./test_channels_movies.txt*
          #rm -rf ./test_channels_united_states.txt*
          #rm -rf ./TW_only.txt*
          rm -rf ./epg_tw.txt*
          #rm -rf ./ytnew.txt*
          rm -rf ./TW1.txt*

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: phpize
          ini-values: extension=opencc

      - name: Install OpenCC
        run: |
          sudo apt-get install opencc

      - name: Start Translate
        run: |
          opencc -i ./TV.txt -o ./TV_TW.txt -c s2t.json
          opencc -i ./TV.txt -o ./TV_TW_tmp.txt -c s2t.json
          opencc -i ./666.txt -o ./app.txt -c s2t.json
          opencc -i ./ETH_cn.txt -o ./ETH.txt -c s2t.json

      - name: Sort TV Channel
        run: |
          chmod +x ./run_SortTV
          ./run_SortTV

           rm -rf ./test_channels_taiwan.txt*
           rm -rf ./test_channels_movies.txt*
           rm -rf ./test_channels_united_states.txt*
           rm -rf ./TW_only.txt*
           rm -rf ./epg_tw.txt*
           rm -rf ./ytnew.txt*
           rm -rf ./TW1.txt*
           rm -rf ./666.txt
           rm -rf ./ETH_cn.txt

          ##echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')" > Update_time
    
           echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S CST')"
           
           # 节目源            
           rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
           echo "Auto Update IPTV in ${{ steps.date.outputs.date }}" > README.md
          
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "Link updated"
          git push
