# This is a basic workflow to help you get started with Actions

name: GetSource

# Controls when the action will run. 
on:
  schedule:
    - cron: '0 0/3 * * *'
    
  pull_request:
    branches:
      - main
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo testing!

      # Runs a set of commands using the runners shell 
      - name: config
        run: |
          git pull
          git config --global user.email "aaa@gmail.com"
          git config --global user.name "aaa"
      
      
      - name: Main
        run: |
          pwd
          #chmod +x autorun.sh
          #./autorun.sh
          wget https://epg.pw/test_channels_taiwan.txt
          
          awk 'NR>12' ./test_channels_taiwan.txt > epg_tw.txt

          echo "外國,#genre#" > movie.txt

          wget https://epg.pw/test_channels_united_states.txt
          wget https://epg.pw/test_channels_movies.txt
          
          grep "Star Movie" ./test_channels_united_states.txt >> movie.txt
          grep "HBO HD" ./test_channels_united_states.txt >> movie.txt
          grep "hbo2" ./test_channels_united_states.txt >> movie.txt
          grep "HBO Family" ./test_channels_united_states.txt >> movie.txt
          grep "HBO Signature" ./test_channels_united_states.txt >> movie.txt
          
          grep "Cinemax" ./test_channels_movies.txt >> movie.txt
          grep "HBO 2"  ./test_channels_movies.txt >> movie.txt
          grep "HBO 3"  ./test_channels_movies.txt >> movie.txt

          wget https://raw.githubusercontent.com/linitfor/MyTV/main/TW_only.txt
          head -n 140 ./TW_only.txt > ytnew.txt

          cat movie.txt  epg_tw.txt > TV1.txt 
          cat ytnew.txt  TV1.txt > TV.txt
          sed -i 's/\[geo\-blocked\]//' ./TV.txt
          
          rm -rf ./test_channels_taiwan.txt*
          rm -rf ./test_channels_movies.txt*
          rm -rf ./test_channels_united_states.txt*
          rm -rf ./TW_only.txt*
          rm -rf ./epg_tw.txt*
          rm -rf ./ytnew.txt*
          rm -rf ./TW1.txt*

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: phpize
          ini-values: extension=opencc

      - name: Install OpenCC
        run: |
          sudo apt-get install opencc

      - name: Start Translate
        run: |
          opencc -i ./TV.txt -o ./TV_TW2.txt -c s2t.json
          opencc -i ./TV.txt -o ./TV_TW_tmp.txt -c s2t.json

      - name: Sort TV Channel
        run: |
          echo "第四台,#genre#" > TV_TW.txt
          grep "民視," ./TV_TW_tmp.txt >> TV_TW.txt
          grep "人間衛視" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "台視", ./TV_TW_tmp.txt >> TV_TW.txt
          grep "大愛," ./TV_TW_tmp.txt >> TV_TW.txt
          grep "中視," ./TV_TW_tmp.txt >> TV_TW.txt
          grep "霹靂台灣" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "華視," ./TV_TW_tmp.txt >> TV_TW.txt
          grep "公視," ./TV_TW_tmp.txt >> TV_TW.txt
          grep "公視台語" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "好消息" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "原住民族電視" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "客家電視" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "BBC Earth" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "Discovery " ./TV_TW_tmp.txt >> TV_TW.txt
          grep "TLC 旅遊生活" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "動物星球" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "CN卡通" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "尼克兒童" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "momo親子" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東森幼幼" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "緯來綜合" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "八大第一" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "八大綜合" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "三立台灣" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "三立都會" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "韓國娛樂台KMTV" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東森綜合" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "超視" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東森購物2" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "momo購物2" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "中天綜合" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東風衛視" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "年代MUCH" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "中天娛樂" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東森戲劇" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "八大戲劇" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "TVBS歡樂" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "緯來戲劇" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "高點電視" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東森購物3" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東森購物1" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "momo購物1" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "三立iNEWS" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "三立Live" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "壹電視新聞" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "年代新聞" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東森新聞" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "華視新聞資訊" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "民視新聞" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "三立新聞" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "三立Live+" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "TVBS新聞" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "TVBS " ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東森財經新聞" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "非凡新聞" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "viva購物1" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東森購物5" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "CATCHPLAY" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東森電影" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "緯來電影" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "LS龍祥電影" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "HBO" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "東森洋片" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "AXN" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "好萊塢電影" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "amc電影" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "CINEMAX" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "緯來育樂" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "緯來體育" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "DAZN 1" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "DAZN 2" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "MOMO綜合" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "博斯運動一" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "緯來日本" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "國興衛視" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "BBC Lifestyle" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "靖天購物一" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "Animax()" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "信吉電視" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "JET 綜合" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "中台灣生活網" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "寰宇新聞" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "鏡電視新聞" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "冠軍電視" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "Z" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "ETtoday綜合" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "非凡商業" ./TV_TW_tmp.txt >> TV_TW.txt
          grep "八大娛樂" ./TV_TW_tmp.txt >> TV_TW.txt
          
       

          
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "Link updated"
          git push
